---
sidebar: sidebar 
permalink: concepts/billing-schedules.html 
keywords: billing schedules, schedule for payment 
summary: Les abonnements Keystone STaaS sont facturés mensuellement et annuellement. 
---
= Découvrez les calendriers de facturation de Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Les abonnements Keystone STaaS sont facturés sur une base mensuelle ou annuelle.



== Facturation mensuelle

Les factures sont envoyées mensuellement.  Pour le mois au cours duquel les services sont utilisés, une facture est envoyée le mois suivant.  Par exemple, la facture des services que vous avez utilisés en janvier est livrée début février.  Cette facture comprend les frais relatifs à la capacité engagée et, le cas échéant, toute utilisation en rafale.



== Facturation annuelle

Une facture est générée au début de chaque année d'abonnement pour le paiement minimum de la capacité engagée.  Il est généré à la date de début de l'abonnement.  Une autre facture est envoyée à la fin d'un trimestre d'abonnement, résumant les frais applicables à toute utilisation intensive accumulée au cours de ce trimestre.  Si la capacité engagée est modifiée au cours d'un abonnement, une facture est envoyée le même jour pour les paiements minimums au prorata pour le reste de cette année d'abonnement.  La facturation est calculée à partir du jour où la modification de la capacité engagée est effective.
