---
sidebar: sidebar 
permalink: concepts/burst-consumption-billing.html 
keywords: burst consumption billing 
summary: La facturation Keystone STaaS est basée sur la capacité de pointe, qui correspond à la capacité que vous consommez, en plus de la capacité engagée de votre abonnement. 
---
= Facturation basée sur la consommation en rafale
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La facturation Keystone STaaS est basée sur la _capacité de pointe_, qui est la capacité que vous consommez, en plus de la capacité engagée de votre abonnement.

Votre limite de rafale est déterminée et spécifiée dans votre contrat Keystone .  C'est 20 % au-dessus de la capacité engagée.

La capacité engagée est la capacité qui vous est accordée lors de l'achat de l'abonnement.  La capacité engagée et la capacité de pointe sont mesurées par niveau de service de performance.  La capacité consommée est la capacité que vos charges de travail utilisent réellement.

Lorsque la capacité consommée est supérieure à la capacité engagée pour un niveau de service de performance, la consommation en rafale est enregistrée et facturée en conséquence.  En général, elle est supérieure de 20 % à la capacité engagée.  L'utilisation au-delà de la capacité d'éclatement est indiquée comme « Au-delà de la limite d'éclatement ».

Ce processus se produit pour chaque enregistrement de consommation généré.  La consommation excessive reflète donc à la fois la quantité et la durée de vos capacités surconsommées en plus de vos capacités engagées.  Pour en savoir plus, consultezlink:../integrations/consumption-tab.html["Consultez les tendances de consommation de vos abonnements Keystone"] .

Pour plus d'informations sur les différentes capacités prises en charge dans Keystone, consultezlink:../concepts/supported-storage-capacity.html["Capacités de stockage prises en charge dans Keystone"] .
