---
sidebar: sidebar 
permalink: concepts/nrnvc.html 
keywords: Non-returnable, non-volatile components, SnapLock compliance, add-on service 
summary: 'Dans le cadre de votre abonnement NetApp Keystone , NetApp étend l"offre NRNVC pour vos services de fichiers, de blocs et d"objets.' 
---
= Composants non retournables et non volatils, et service complémentaire de conformité SnapLock pour Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dans le cadre de votre abonnement NetApp Keystone , NetApp étend l'offre de composants non retournables et non volatils (NRNVC) pour vos services de fichiers, de blocs et d'objets.

NetApp ne récupère pas les supports de stockage physiques utilisés pendant toute la durée du service ou à la fin du service lorsque NetApp récupère par ailleurs tous ses actifs physiques utilisés dans la fourniture du service.

Vous pouvez vous abonner à ce service complémentaire dans le cadre de votre abonnement Keystone .  Si vous avez acheté ce service, veuillez noter les points suivants :

* Vous n'avez pas besoin de retourner les lecteurs et la mémoire non volatile à la fin de la période de service ou s'ils sont tombés en panne ou ont été jugés défectueux pendant la période de service.
* Cependant, vous devez produire un certificat de destruction pour les lecteurs et/ou la mémoire non volatile et ne pouvez pas les utiliser à d'autres fins.
* Le coût supplémentaire associé au NRNVC est facturé en pourcentage de la facture mensuelle totale des services d'abonnement (y compris le service standard, la protection avancée des données et la hiérarchisation des données).
* Ce service s'applique uniquement aux services de fichiers, de blocs et d'objets.


Pour plus d'informations sur les services standard et cloud, consultezlink:supported-storage-services.html["Services STaaS Keystone"] .

Pour plus d'informations sur les niveaux de service de performance, voirlink:../concepts/service-levels.html["Niveaux de service de performance dans Keystone"] .



== Conformité SnapLock

La technologie SnapLock active la fonction NRNVC en rendant le lecteur inutilisable après la date d'expiration définie dans le volume.  Pour utiliser la technologie SnapLock sur vos volumes, vous devez vous abonner à NRNVC.  Ceci s'applique uniquement aux services de fichiers et de blocs.

Pour plus d'informations sur la technologie SnapLock , consultez https://docs.netapp.com/us-en/ontap/snaplock/snaplock-concept.html["Qu'est-ce que SnapLock"^] .
