---
sidebar: sidebar 
permalink: concepts/pricing.html 
keywords: pricing, billing introduction, Keystone billing 
summary: Keystone propose un modèle de paiement à mesure de votre croissance pour vos besoins de consommation flexibles et évolutifs. 
---
= Tarification Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Le service d'abonnement à la carte NetApp Keystone STaaS offre une consommation flexible et évolutive avec une tarification prévisible et à l'avance pour vos besoins de stockage.

Keystone vous propose les services de facturation suivants :

* Vous pouvez payer en fonction des IOPS et de la capacité de latence engagée pour répondre à divers besoins de charge de travail. Les différents niveaux de service de performances (Extreme, Premium, Performance, Standard, Value et Object) vous permettent de gérer votre stockage en fonction du niveau de service de performances que vous avez acheté.
* Il présente une facturation prévisible pour la capacité engagée et un paiement à l'utilisation pour une utilisation variable (en rafale) de la capacité.
* Vous pouvez sélectionner un prix groupé pour le matériel, le système d'exploitation principal et le support pour un prix unique $/Tio.  Vous disposez d'une facture unique pour chaque type de stockage, fichier, bloc, objet ou service de stockage cloud.
* Vous pouvez sélectionner une durée flexible pour les services et les options de paiement, telles que mensuellement, trimestriellement ou annuellement.


La facturation Keystone est basée sur la capacité engagée et la consommation variable en rafale.

Pour plus d'informations sur les différentes capacités prises en charge dans Keystone, consultezlink:../concepts/supported-storage-capacity.html["Capacités de stockage prises en charge dans Keystone"] .

*Informations connexes*

* link:../concepts/committed-capacity-billing.html["Facturation basée sur la capacité engagée"]
* link:../concepts/consumed-capacity-billing.html["Comptage basé sur la capacité consommée"]
* link:../concepts/burst-consumption-billing.html["Facturation basée sur la consommation en rafale"]
* link:../concepts/misc-volume-billing.html["Facturation basée sur divers types de volumes"]
* link:../concepts/billing-schedules.html["Calendriers de facturation"]

