---
sidebar: sidebar 
permalink: concepts/service-levels.html 
keywords: service levels, service level, rate plan or service level 
summary: Keystone STaaS offre une capacité de stockage à des niveaux de service prédéfinis.  Chaque volume géré par Keystone est associé à un niveau de service. 
---
= Niveaux de service de performance dans Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS offre une capacité de stockage de données à des niveaux de service de performance prédéfinis.  Chaque volume géré par les services Keystone est associé à un niveau de service de performance.

Un abonnement peut avoir plusieurs plans tarifaires et chaque plan tarifaire correspond à un niveau de service de performance.  Chaque plan tarifaire dispose d'une capacité engagée par niveau de service de performance.

Chaque niveau de service de performance est défini par sa densité d'E/S, c'est-à-dire IOPS/Tio/volume.  Il s'agit du rapport entre les performances (opérations d'entrée/sortie par seconde [IOPS]) et la capacité de stockage utilisée (Tio), qui est IOPS/Tio à latence moyenne par volume.

Vous sélectionnez les niveaux de service de performances en fonction de votre environnement de stockage et de vos besoins de stockage et de consommation.  Les niveaux de service de performances de base sont disponibles pour vous par défaut.  Des niveaux de service de performance spécifiques sont également disponibles, si vous avez opté pour des services complémentaires.  Par exemple, pour le service complémentaire de protection avancée des données, le niveau de service de performance _Advanced Data-Protect_ est attribué à votre abonnement.


TIP: Une description détaillée du service pour les niveaux de service de performance NetApp Keystone STaaS est disponible https://www.netapp.com/services/keystone/terms-and-conditions/["ici"^] .

Les niveaux de service de performances de base pour les types de stockage pris en charge, les services de fichiers, de blocs, d'objets et de cloud sont décrits dans les sections suivantes :



== Niveaux de service de performance pour le stockage de fichiers et de blocs

*Protocoles pris en charge* : NFS, CIFS, iSCSI et FC

|===


| *Niveau de service de performance* | *Extrême* | *Prime* | *Performance* | *Standard* | *Valeur* 


| *Exemples de types de charges de travail* | Analyses, bases de données, applications critiques | VDI, VSI, développement logiciel | OLTP, OLAP, conteneurs, développement de logiciels | Partages de fichiers, serveurs Web | Sauvegarde 


| *Nombre maximal d'IOPS/Tio logiques stockés par volume* | 12 288 | 4 096 | 2 048 | 512 | 128 


| *Nombre maximal d'IOPS/Tio logiques alloués par volume* | 6 144 | 2 048 | 1 024 | 256 | 64 


| *Nombre maximal de Mo/s/Tio logiques stockés par volume à 32 Ko/s* | 384 | 128 | 64 | 16 | 4 


| *Latence cible du 90e percentile* | <1 ms | <2 ms | <4 ms | <4 ms | <17 ms 


| *Taille du bloc* 5+| 32K 


| *Type de capacité engagée et mesurée* 5+| Logique 
|===


=== En savoir plus sur les niveaux de service de performance pour le stockage de fichiers et de blocs

Les mesures de niveau de service de performance de base dépendent des conditions suivantes :

* Les niveaux de service de performances pour le stockage de fichiers et de blocs prennent en charge ONTAP 9.7 et versions ultérieures.
* Les valeurs IOPS/Tio/volume, MBps/Tio/volume et de latence pour les niveaux de service de performances sont basées sur la quantité de données stockées dans le volume, la taille du bloc de 32 Ko et une combinaison aléatoire de 70 % d'opérations d'E/S en lecture et 30 % en écriture.
* Les IOPS/Tio/volume et les Mbit/s/Tio/volume réels peuvent varier en fonction de la taille réelle ou supposée du bloc, de la concurrence de la charge de travail du système ou des opérations d'entrée-sortie.
* La latence n'inclut pas les éléments suivants :
+
** latence de l'application ou de l'hôte
** latence du réseau client vers ou depuis les ports du contrôleur
** frais généraux associés au transfert de données vers le magasin d'objets dans le cas de FabricPool
** latence appliquée automatiquement par QoS pour maintenir les E/S dans les limites maximales de niveau de service de performance


* Les valeurs de latence ne s'appliquent pas aux opérations d'écriture MetroCluster .  Ces opérations d’écriture dépendent de la distance des systèmes distants.
* Si un ou plusieurs volumes d'un système de stockage ne disposent pas d'une stratégie AQoS attribuée, ces volumes sont considérés comme non conformes et aucun niveau de service de performances cible n'est applicable pour ces systèmes.
* _Les IOPS attendues_ sont ciblées pour FabricPool uniquement si la stratégie de hiérarchisation est définie sur « aucune » et qu'aucun bloc ne se trouve dans le cloud.  _Les IOPS attendues_ sont ciblées pour les volumes qui ne sont pas dans une relation synchrone SnapMirror .
* Les opérations d'E/S de charge de travail doivent être équilibrées sur tous les contrôleurs déployés, comme déterminé par l'ordre Keystone .




== Stockage d'objets

*Protocole pris en charge* : S3

|===


| *Niveau de service de performance* | Objet 


| *Type de charge de travail* | Dépôt de médias, archivage 


| *Nombre maximal d'IOPS/TiB logiques stockés par volume* | S/O 


| *Nombre maximal de Mo/s/Tio logique stockés par volume* | S/O 


| *Latence moyenne* | S/O 


| *Type de capacité engagée et mesurée* | Physique 
|===

NOTE: La latence n'inclut pas les frais généraux associés au transfert de données vers le magasin d'objets dans le cas du stockage FabricPool .



== Stockage en nuage

*Protocole pris en charge* : NFS, CIFS, iSCSI et S3 (AWS et Azure uniquement)

|===


| *Niveau de service de performance* | Cloud Volumes ONTAP 


| *Type de charge de travail* | Reprise après sinistre, développement/test de logiciels, applications professionnelles 


| *Nombre maximal d'IOPS/TiB logiques stockés par volume* | S/O 


| *Nombre maximal de Mo/s/Tio logique stockés par volume* | S/O 


| *Latence moyenne* | S/O 
|===
[NOTE]
====
* Les services cloud natifs, tels que le calcul, le stockage et la mise en réseau, sont facturés par les fournisseurs de cloud.
* Ces services dépendent des caractéristiques de stockage et de calcul du cloud.


====
*Informations connexes*

* link:../concepts/supported-storage-capacity.html["Capacités de stockage prises en charge"]
* link:..//concepts/metrics.html["Mesures et définitions utilisées dans les services Keystone"]
* link:../concepts/qos.html["Qualité de service (QoS) dans Keystone"]
* link:../concepts/pricing.html["Tarification Keystone"]

