---
sidebar: sidebar 
permalink: concepts/supported-storage-capacity.html 
keywords: storage capacity, capacity definition, keystone STaaS storage capacity, 
summary: Découvrez les types de capacités de stockage prises en charge par le service NetApp Keystone STaaS pour la version 2. 
---
= Capacités de stockage prises en charge dans Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Le service NetApp Keystone STaaS prend en charge plusieurs types de capacités de stockage.  Comprendre ces différents termes de capacité peut vous aider lorsque vous utilisez Keystone.



[[logical-capacity]]
== Capacité logique

Il s'agit de la capacité de stockage requise pour stocker les données utilisateur avant que toute efficacité des données fournie par la baie de stockage ne soit appliquée.



[[committed-capacity]]
== Capacité engagée

La capacité logique minimale facturée chaque mois pendant l'abonnement :

* La capacité est engagée pour chaque niveau de service de performance.
* Des capacités engagées et des niveaux de service supplémentaires peuvent être ajoutés au cours de la durée.




[[changes-to-committed-capacity]]
=== Modifications de la capacité engagée

Pendant la durée d'un abonnement, vous pouvez modifier les capacités engagées.  Cependant, certaines conditions préalables sont requises :

* La capacité engagée peut être diminuée en fonction de certaines conditions.  Pour plus d'informations, voirlink:../concepts/capacity-requirements.html["Réduction de capacité"] .
* La capacité engagée ne peut pas être augmentée 90 jours avant l'expiration de votre abonnement, sauf si l'abonnement doit être renouvelé pour une durée supplémentaire de 12 mois.
* Vous pouvez demander des modifications de la capacité engagée via la Console ou depuis votre Keystone Success Manager (KSM). Pour plus d'informations sur la procédure de demande de modifications, veuillez consulter la section correspondante. link:../concepts/support-services.html["Prise en charge de NetApp Keystone"].




[[consumed-capacity]]
== Capacité consommée

La capacité consommée correspond à la capacité (en Tio de stockage) actuellement utilisée par le service. Elle est calculée différemment selon le type de stockage des données :

* *Stockage unifié ou optimisé par blocs* : La capacité consommée est calculée en fonction du type de capacité (logique ou physique) sélectionné lors du processus de commande. Le calcul est effectué par instance de niveau de service de performance.
+
.. *Capacité logique* : Il s'agit de la somme de :
+
*** Capacité logique mesurée, avant prise en compte des efficacités des baies de stockage, pour stocker toutes les instances et tous les types de données client, tels que les copies, les copies en miroir, les versions et les clones.
*** Capacité physique utilisée pour stocker les métadonnées et les données différentielles des instantanés et de certains clones.
*** Toute capacité physique à provisionnement épais.


.. *Capacité physique* : Il s'agit de la somme de :
+
*** Capacité physique mesurée, après optimisation des données de la baie de stockage, pour stocker toutes les instances et tous les types de données client, tels que les copies, les copies en miroir, les versions et les clones.
*** Capacité physique utilisée pour stocker les métadonnées et les données différentielles des instantanés.
*** Toute capacité physique à provisionnement épais.




* *Stockage d'objets* : La capacité consommée correspond à la quantité de capacité physique mesurée utilisée pour stocker toutes les instances et tous les types de données client sur l'ensemble des nœuds. Ce calcul repose sur les politiques de gestion du cycle de vie des informations (ILM) configurées.
* *Cloud Volumes ONTAP* : La capacité consommée est calculée comme la quantité de capacité logique provisionnée mesurée de tous les volumes Cloud Volumes ONTAP.




[[burst-capacity]]
== Capacité d'éclatement

Le service NetApp Keystone vous permet d'utiliser une capacité supplémentaire en plus de la capacité engagée pour un niveau de service.  C'est ce qu'on appelle l'utilisation de la capacité en rafale.

Notez ces points :

* La capacité de rupture est convenue dans l’accord Keystone .  Elle est généralement fixée à 20 % au-dessus de la capacité engagée et est facturée au même tarif que la capacité engagée.
* La capacité de pointe peut être consommée sur une base élastique et est facturée quotidiennement en fonction de la moyenne consommée.




[[billed-capacity]]
== Capacité facturée

Facture mensuelle = (capacité engagée [Tio] * tarif engagé [$/Tio]) + (capacité de rafale provisionnée moyenne quotidienne [Tio] * tarif de rafale [$/Tio]).  La facture mensuelle contient des frais minimums basés sur la capacité engagée.

La facture mensuelle varie au-delà du tarif minimum en fonction de la consommation moyenne quotidienne de capacité de pointe.
