---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: netapp, keystone, release notes, known issues 
summary: Les problèmes connus identifient les problèmes qui pourraient vous empêcher d’utiliser Keystone efficacement. 
---
= Problèmes connus dans Keystone STaaS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Les problèmes connus identifient les problèmes qui pourraient vous empêcher d’utiliser Keystone STaaS efficacement.

Les problèmes connus suivants sont signalés dans NetApp Keystone STaaS :

[cols="3*"]
|===
| Problème connu | Description | Solution de contournement 


 a| 
Facture incorrecte en raison d'une incompatibilité de données
 a| 
Une incohérence dans les données de consommation des abonnements AutoSupport entraîne la génération de factures incorrectes, entraînant des inexactitudes de facturation.
 a| 
Aucune



 a| 
Affichage incorrect du type de politique QoS
 a| 
Dans l'onglet *Détails du volume*, la colonne *Type de politique QoS* affiche _QoS_ lorsqu'aucune politique QoS n'est appliquée, et la colonne Conforme affiche _Non défini_, ce qui entraîne une incohérence dans l'état de la politique QoS affiché.
 a| 
Aucune



 a| 
Les détails du volume ne sont pas disponibles pour les abonnements principaux et liés
 a| 
L'onglet *Résumé du volume* affiche zéro pour le nombre total de volumes, l'état de conformité QoS, le nombre de volumes protégés et la capacité totale consommée pour les abonnements principaux et secondaires liés.
 a| 
Aucune

|===